spring:
  profiles:
    active: dev
  data:
    mongodb:
      database: nichan
logging:
    file: logs/myapp.log
    level:
        org.springframework.web: INFO
---
spring:
  profiles: dev
  thymeleaf:
    cache: false
app:
  host-name: 192.168.1.3
---
spring:
  profiles: prod
app:
  host-name: ec2-52-197-46-233.ap-northeast-1.compute.amazonaws.com