spring:
  profiles:
    active: dev
  data:
    mongodb:
      database: nichan
---
spring:
  profiles: dev
  thymeleaf:
    cache: false
app:
  host-name: 192.168.1.3
---
spring:
  profiles: prod
app:
  host-name: 128.199.129.51